import React, { FC } from "react";
import { CountryCode, CountryName } from "../../types";
import { Text, TextStyle } from "react-native";

export const countryOptions: {
  key: string;
  iso: string;
  flag: string;
  name: string;
}[] = [
  {
    key: "AD",
    iso: "AD",
    flag: "🇦🇩",
    name: "Andorra",
  },
  {
    key: "AE",
    iso: "AE",
    flag: "🇦🇪",
    name: "United Arab Emirates",
  },
  {
    key: "AF",
    iso: "AF",
    flag: "🇦🇫",
    name: "Afghanistan",
  },
  {
    key: "AG",
    iso: "AG",
    flag: "🇦🇬",
    name: "Antigua and Barbuda",
  },
  {
    key: "AI",
    iso: "AI",
    flag: "🇦🇮",
    name: "Anguilla",
  },
  {
    key: "AL",
    iso: "AL",
    flag: "🇦🇱",
    name: "Albania",
  },
  {
    key: "AM",
    iso: "AM",
    flag: "🇦🇲",
    name: "Armenia",
  },
  {
    key: "AO",
    iso: "AO",
    flag: "🇦🇴",
    name: "Angola",
  },
  {
    key: "AQ",
    iso: "AQ",
    flag: "🇦🇶",
    name: "Antarctica",
  },
  {
    key: "AR",
    iso: "AR",
    flag: "🇦🇷",
    name: "Argentina",
  },
  {
    key: "AS",
    iso: "AS",
    flag: "🇦🇸",
    name: "American Samoa",
  },
  {
    key: "AT",
    iso: "AT",
    flag: "🇦🇹",
    name: "Austria",
  },
  {
    key: "AU",
    iso: "AU",
    flag: "🇦🇺",
    name: "Australia",
  },
  {
    key: "AW",
    iso: "AW",
    flag: "🇦🇼",
    name: "Aruba",
  },
  {
    key: "AX",
    iso: "AX",
    flag: "🇦🇽",
    name: "Åland Islands",
  },
  {
    key: "AZ",
    iso: "AZ",
    flag: "🇦🇿",
    name: "Azerbaijan",
  },
  {
    key: "BA",
    iso: "BA",
    flag: "🇧🇦",
    name: "Bosnia and Herzegovina",
  },
  {
    key: "BB",
    iso: "BB",
    flag: "🇧🇧",
    name: "Barbados",
  },
  {
    key: "BD",
    iso: "BD",
    flag: "🇧🇩",
    name: "Bangladesh",
  },
  {
    key: "BE",
    iso: "BE",
    flag: "🇧🇪",
    name: "Belgium",
  },
  {
    key: "BF",
    iso: "BF",
    flag: "🇧🇫",
    name: "Burkina Faso",
  },
  {
    key: "BG",
    iso: "BG",
    flag: "🇧🇬",
    name: "Bulgaria",
  },
  {
    key: "BH",
    iso: "BH",
    flag: "🇧🇭",
    name: "Bahrain",
  },
  {
    key: "BI",
    iso: "BI",
    flag: "🇧🇮",
    name: "Burundi",
  },
  {
    key: "BJ",
    iso: "BJ",
    flag: "🇧🇯",
    name: "Benin",
  },
  {
    key: "BL",
    iso: "BL",
    flag: "🇧🇱",
    name: "Saint Barthélemy",
  },
  {
    key: "BM",
    iso: "BM",
    flag: "🇧🇲",
    name: "Bermuda",
  },
  {
    key: "BN",
    iso: "BN",
    flag: "🇧🇳",
    name: "Brunei Darussalam",
  },
  {
    key: "BO",
    iso: "BO",
    flag: "🇧🇴",
    name: "Bolivia",
  },
  {
    key: "BQ",
    iso: "BQ",
    flag: "🇧🇶",
    name: "Bonaire, Sint Eustatius and Saba",
  },
  {
    key: "BR",
    iso: "BR",
    flag: "🇧🇷",
    name: "Brazil",
  },
  {
    key: "BS",
    iso: "BS",
    flag: "🇧🇸",
    name: "Bahamas",
  },
  {
    key: "BT",
    iso: "BT",
    flag: "🇧🇹",
    name: "Bhutan",
  },
  {
    key: "BV",
    iso: "BV",
    flag: "🇧🇻",
    name: "Bouvet Island",
  },
  {
    key: "BW",
    iso: "BW",
    flag: "🇧🇼",
    name: "Botswana",
  },
  {
    key: "BY",
    iso: "BY",
    flag: "🇧🇾",
    name: "Belarus",
  },
  {
    key: "BZ",
    iso: "BZ",
    flag: "🇧🇿",
    name: "Belize",
  },
  {
    key: "CA",
    iso: "CA",
    flag: "🇨🇦",
    name: "Canada",
  },
  {
    key: "CC",
    iso: "CC",
    flag: "🇨🇨",
    name: "Cocos (Keeling) Islands",
  },
  {
    key: "CD",
    iso: "CD",
    flag: "🇨🇩",
    name: "Congo Kinshasa",
  },
  {
    key: "CF",
    iso: "CF",
    flag: "🇨🇫",
    name: "Central African Republic",
  },
  {
    key: "CG",
    iso: "CG",
    flag: "🇨🇬",
    name: "Congo Brazzaville",
  },
  {
    key: "CH",
    iso: "CH",
    flag: "🇨🇭",
    name: "Switzerland",
  },
  {
    key: "CI",
    iso: "CI",
    flag: "🇨🇮",
    name: "Côte D'Ivoire",
  },
  {
    key: "CK",
    iso: "CK",
    flag: "🇨🇰",
    name: "Cook Islands",
  },
  {
    key: "CL",
    iso: "CL",
    flag: "🇨🇱",
    name: "Chile",
  },
  {
    key: "CM",
    iso: "CM",
    flag: "🇨🇲",
    name: "Cameroon",
  },
  {
    key: "CN",
    iso: "CN",
    flag: "🇨🇳",
    name: "China",
  },
  {
    key: "CO",
    iso: "CO",
    flag: "🇨🇴",
    name: "Colombia",
  },
  {
    key: "CR",
    iso: "CR",
    flag: "🇨🇷",
    name: "Costa Rica",
  },
  {
    key: "CU",
    iso: "CU",
    flag: "🇨🇺",
    name: "Cuba",
  },
  {
    key: "CV",
    iso: "CV",
    flag: "🇨🇻",
    name: "Cape Verde",
  },
  {
    key: "CW",
    iso: "CW",
    flag: "🇨🇼",
    name: "Curaçao",
  },
  {
    key: "CX",
    iso: "CX",
    flag: "🇨🇽",
    name: "Christmas Island",
  },
  {
    key: "CY",
    iso: "CY",
    flag: "🇨🇾",
    name: "Cyprus",
  },
  {
    key: "CZ",
    iso: "CZ",
    flag: "🇨🇿",
    name: "Czech Republic",
  },
  {
    key: "DE",
    iso: "DE",
    flag: "🇩🇪",
    name: "Germany",
  },
  {
    key: "DJ",
    iso: "DJ",
    flag: "🇩🇯",
    name: "Djibouti",
  },
  {
    key: "DK",
    iso: "DK",
    flag: "🇩🇰",
    name: "Denmark",
  },
  {
    key: "DM",
    iso: "DM",
    flag: "🇩🇲",
    name: "Dominica",
  },
  {
    key: "DO",
    iso: "DO",
    flag: "🇩🇴",
    name: "Dominican Republic",
  },
  {
    key: "DZ",
    iso: "DZ",
    flag: "🇩🇿",
    name: "Algeria",
  },
  {
    key: "EC",
    iso: "EC",
    flag: "🇪🇨",
    name: "Ecuador",
  },
  {
    key: "EE",
    iso: "EE",
    flag: "🇪🇪",
    name: "Estonia",
  },
  {
    key: "EG",
    iso: "EG",
    flag: "🇪🇬",
    name: "Egypt",
  },
  {
    key: "EH",
    iso: "EH",
    flag: "🇪🇭",
    name: "Western Sahara",
  },
  {
    key: "ER",
    iso: "ER",
    flag: "🇪🇷",
    name: "Eritrea",
  },
  {
    key: "ES",
    iso: "ES",
    flag: "🇪🇸",
    name: "Spain",
  },
  {
    key: "ET",
    iso: "ET",
    flag: "🇪🇹",
    name: "Ethiopia",
  },
  {
    key: "FI",
    iso: "FI",
    flag: "🇫🇮",
    name: "Finland",
  },
  {
    key: "FJ",
    iso: "FJ",
    flag: "🇫🇯",
    name: "Fiji",
  },
  {
    key: "FK",
    iso: "FK",
    flag: "🇫🇰",
    name: "Falkland Islands (Malvinas)",
  },
  {
    key: "FM",
    iso: "FM",
    flag: "🇫🇲",
    name: "Micronesia",
  },
  {
    key: "FO",
    iso: "FO",
    flag: "🇫🇴",
    name: "Faroe Islands",
  },
  {
    key: "FR",
    iso: "FR",
    flag: "🇫🇷",
    name: "France",
  },
  {
    key: "GA",
    iso: "GA",
    flag: "🇬🇦",
    name: "Gabon",
  },
  {
    key: "GB",
    iso: "GB",
    flag: "🇬🇧",
    name: "United Kingdom",
  },
  {
    key: "GD",
    iso: "GD",
    flag: "🇬🇩",
    name: "Grenada",
  },
  {
    key: "GE",
    iso: "GE",
    flag: "🇬🇪",
    name: "Georgia",
  },
  {
    key: "GF",
    iso: "GF",
    flag: "🇬🇫",
    name: "French Guiana",
  },
  {
    key: "GG",
    iso: "GG",
    flag: "🇬🇬",
    name: "Guernsey",
  },
  {
    key: "GH",
    iso: "GH",
    flag: "🇬🇭",
    name: "Ghana",
  },
  {
    key: "GI",
    iso: "GI",
    flag: "🇬🇮",
    name: "Gibraltar",
  },
  {
    key: "GL",
    iso: "GL",
    flag: "🇬🇱",
    name: "Greenland",
  },
  {
    key: "GM",
    iso: "GM",
    flag: "🇬🇲",
    name: "Gambia",
  },
  {
    key: "GN",
    iso: "GN",
    flag: "🇬🇳",
    name: "Guinea",
  },
  {
    key: "GP",
    iso: "GP",
    flag: "🇬🇵",
    name: "Guadeloupe",
  },
  {
    key: "GQ",
    iso: "GQ",
    flag: "🇬🇶",
    name: "Equatorial Guinea",
  },
  {
    key: "GR",
    iso: "GR",
    flag: "🇬🇷",
    name: "Greece",
  },
  {
    key: "GS",
    iso: "GS",
    flag: "🇬🇸",
    name: "South Georgia",
  },
  {
    key: "GT",
    iso: "GT",
    flag: "🇬🇹",
    name: "Guatemala",
  },
  {
    key: "GU",
    iso: "GU",
    flag: "🇬🇺",
    name: "Guam",
  },
  {
    key: "GW",
    iso: "GW",
    flag: "🇬🇼",
    name: "Guinea-Bissau",
  },
  {
    key: "GY",
    iso: "GY",
    flag: "🇬🇾",
    name: "Guyana",
  },
  {
    key: "HK",
    iso: "HK",
    flag: "🇭🇰",
    name: "Hong Kong",
  },
  {
    key: "HM",
    iso: "HM",
    flag: "🇭🇲",
    name: "Heard Island and Mcdonald Islands",
  },
  {
    key: "HN",
    iso: "HN",
    flag: "🇭🇳",
    name: "Honduras",
  },
  {
    key: "HR",
    iso: "HR",
    flag: "🇭🇷",
    name: "Croatia",
  },
  {
    key: "HT",
    iso: "HT",
    flag: "🇭🇹",
    name: "Haiti",
  },
  {
    key: "HU",
    iso: "HU",
    flag: "🇭🇺",
    name: "Hungary",
  },
  {
    key: "ID",
    iso: "ID",
    flag: "🇮🇩",
    name: "Indonesia",
  },
  {
    key: "IE",
    iso: "IE",
    flag: "🇮🇪",
    name: "Ireland",
  },
  {
    key: "IL",
    iso: "IL",
    flag: "🇮🇱",
    name: "Israel",
  },
  {
    key: "IM",
    iso: "IM",
    flag: "🇮🇲",
    name: "Isle of Man",
  },
  {
    key: "IN",
    iso: "IN",
    flag: "🇮🇳",
    name: "India",
  },
  {
    key: "IO",
    iso: "IO",
    flag: "🇮🇴",
    name: "British Indian Ocean Territory",
  },
  {
    key: "IQ",
    iso: "IQ",
    flag: "🇮🇶",
    name: "Iraq",
  },
  {
    key: "IR",
    iso: "IR",
    flag: "🇮🇷",
    name: "Iran",
  },
  {
    key: "IS",
    iso: "IS",
    flag: "🇮🇸",
    name: "Iceland",
  },
  {
    key: "IT",
    iso: "IT",
    flag: "🇮🇹",
    name: "Italy",
  },
  {
    key: "JE",
    iso: "JE",
    flag: "🇯🇪",
    name: "Jersey",
  },
  {
    key: "JM",
    iso: "JM",
    flag: "🇯🇲",
    name: "Jamaica",
  },
  {
    key: "JO",
    iso: "JO",
    flag: "🇯🇴",
    name: "Jordan",
  },
  {
    key: "JP",
    iso: "JP",
    flag: "🇯🇵",
    name: "Japan",
  },
  {
    key: "KE",
    iso: "KE",
    flag: "🇰🇪",
    name: "Kenya",
  },
  {
    key: "KG",
    iso: "KG",
    flag: "🇰🇬",
    name: "Kyrgyzstan",
  },
  {
    key: "KH",
    iso: "KH",
    flag: "🇰🇭",
    name: "Cambodia",
  },
  {
    key: "KI",
    iso: "KI",
    flag: "🇰🇮",
    name: "Kiribati",
  },
  {
    key: "KM",
    iso: "KM",
    flag: "🇰🇲",
    name: "Comoros",
  },
  {
    key: "KN",
    iso: "KN",
    flag: "🇰🇳",
    name: "Saint Kitts and Nevis",
  },
  {
    key: "KP",
    iso: "KP",
    flag: "🇰🇵",
    name: "North Korea",
  },
  {
    key: "KR",
    iso: "KR",
    flag: "🇰🇷",
    name: "South Korea",
  },
  {
    key: "KW",
    iso: "KW",
    flag: "🇰🇼",
    name: "Kuwait",
  },
  {
    key: "KY",
    iso: "KY",
    flag: "🇰🇾",
    name: "Cayman Islands",
  },
  {
    key: "KZ",
    iso: "KZ",
    flag: "🇰🇿",
    name: "Kazakhstan",
  },
  {
    key: "LA",
    iso: "LA",
    flag: "🇱🇦",
    name: "Lao People's Democratic Republic",
  },
  {
    key: "LB",
    iso: "LB",
    flag: "🇱🇧",
    name: "Lebanon",
  },
  {
    key: "LC",
    iso: "LC",
    flag: "🇱🇨",
    name: "Saint Lucia",
  },
  {
    key: "LI",
    iso: "LI",
    flag: "🇱🇮",
    name: "Liechtenstein",
  },
  {
    key: "LK",
    iso: "LK",
    flag: "🇱🇰",
    name: "Sri Lanka",
  },
  {
    key: "LR",
    iso: "LR",
    flag: "🇱🇷",
    name: "Liberia",
  },
  {
    key: "LS",
    iso: "LS",
    flag: "🇱🇸",
    name: "Lesotho",
  },
  {
    key: "LT",
    iso: "LT",
    flag: "🇱🇹",
    name: "Lithuania",
  },
  {
    key: "LU",
    iso: "LU",
    flag: "🇱🇺",
    name: "Luxembourg",
  },
  {
    key: "LV",
    iso: "LV",
    flag: "🇱🇻",
    name: "Latvia",
  },
  {
    key: "LY",
    iso: "LY",
    flag: "🇱🇾",
    name: "Libya",
  },
  {
    key: "MA",
    iso: "MA",
    flag: "🇲🇦",
    name: "Morocco",
  },
  {
    key: "MC",
    iso: "MC",
    flag: "🇲🇨",
    name: "Monaco",
  },
  {
    key: "MD",
    iso: "MD",
    flag: "🇲🇩",
    name: "Moldova",
  },
  {
    key: "ME",
    iso: "ME",
    flag: "🇲🇪",
    name: "Montenegro",
  },
  {
    key: "MF",
    iso: "MF",
    flag: "🇲🇫",
    name: "Saint Martin (French Part)",
  },
  {
    key: "MG",
    iso: "MG",
    flag: "🇲🇬",
    name: "Madagascar",
  },
  {
    key: "MH",
    iso: "MH",
    flag: "🇲🇭",
    name: "Marshall Islands",
  },
  {
    key: "MK",
    iso: "MK",
    flag: "🇲🇰",
    name: "Macedonia",
  },
  {
    key: "ML",
    iso: "ML",
    flag: "🇲🇱",
    name: "Mali",
  },
  {
    key: "MM",
    iso: "MM",
    flag: "🇲🇲",
    name: "Myanmar",
  },
  {
    key: "MN",
    iso: "MN",
    flag: "🇲🇳",
    name: "Mongolia",
  },
  {
    key: "MO",
    iso: "MO",
    flag: "🇲🇴",
    name: "Macao",
  },
  {
    key: "MP",
    iso: "MP",
    flag: "🇲🇵",
    name: "Northern Mariana Islands",
  },
  {
    key: "MQ",
    iso: "MQ",
    flag: "🇲🇶",
    name: "Martinique",
  },
  {
    key: "MR",
    iso: "MR",
    flag: "🇲🇷",
    name: "Mauritania",
  },
  {
    key: "MS",
    iso: "MS",
    flag: "🇲🇸",
    name: "Montserrat",
  },
  {
    key: "MT",
    iso: "MT",
    flag: "🇲🇹",
    name: "Malta",
  },
  {
    key: "MU",
    iso: "MU",
    flag: "🇲🇺",
    name: "Mauritius",
  },
  {
    key: "MV",
    iso: "MV",
    flag: "🇲🇻",
    name: "Maldives",
  },
  {
    key: "MW",
    iso: "MW",
    flag: "🇲🇼",
    name: "Malawi",
  },
  {
    key: "MX",
    iso: "MX",
    flag: "🇲🇽",
    name: "Mexico",
  },
  {
    key: "MY",
    iso: "MY",
    flag: "🇲🇾",
    name: "Malaysia",
  },
  {
    key: "MZ",
    iso: "MZ",
    flag: "🇲🇿",
    name: "Mozambique",
  },
  {
    key: "NA",
    iso: "NA",
    flag: "🇳🇦",
    name: "Namibia",
  },
  {
    key: "NC",
    iso: "NC",
    flag: "🇳🇨",
    name: "New Caledonia",
  },
  {
    key: "NE",
    iso: "NE",
    flag: "🇳🇪",
    name: "Niger",
  },
  {
    key: "NF",
    iso: "NF",
    flag: "🇳🇫",
    name: "Norfolk Island",
  },
  {
    key: "NG",
    iso: "NG",
    flag: "🇳🇬",
    name: "Nigeria",
  },
  {
    key: "NI",
    iso: "NI",
    flag: "🇳🇮",
    name: "Nicaragua",
  },
  {
    key: "NL",
    iso: "NL",
    flag: "🇳🇱",
    name: "Netherlands",
  },
  {
    key: "NO",
    iso: "NO",
    flag: "🇳🇴",
    name: "Norway",
  },
  {
    key: "NP",
    iso: "NP",
    flag: "🇳🇵",
    name: "Nepal",
  },
  {
    key: "NR",
    iso: "NR",
    flag: "🇳🇷",
    name: "Nauru",
  },
  {
    key: "NU",
    iso: "NU",
    flag: "🇳🇺",
    name: "Niue",
  },
  {
    key: "NZ",
    iso: "NZ",
    flag: "🇳🇿",
    name: "New Zealand",
  },
  {
    key: "OM",
    iso: "OM",
    flag: "🇴🇲",
    name: "Oman",
  },
  {
    key: "PA",
    iso: "PA",
    flag: "🇵🇦",
    name: "Panama",
  },
  {
    key: "PE",
    iso: "PE",
    flag: "🇵🇪",
    name: "Peru",
  },
  {
    key: "PF",
    iso: "PF",
    flag: "🇵🇫",
    name: "French Polynesia",
  },
  {
    key: "PG",
    iso: "PG",
    flag: "🇵🇬",
    name: "Papua New Guinea",
  },
  {
    key: "PH",
    iso: "PH",
    flag: "🇵🇭",
    name: "Philippines",
  },
  {
    key: "PK",
    iso: "PK",
    flag: "🇵🇰",
    name: "Pakistan",
  },
  {
    key: "PL",
    iso: "PL",
    flag: "🇵🇱",
    name: "Poland",
  },
  {
    key: "PM",
    iso: "PM",
    flag: "🇵🇲",
    name: "Saint Pierre and Miquelon",
  },
  {
    key: "PN",
    iso: "PN",
    flag: "🇵🇳",
    name: "Pitcairn",
  },
  {
    key: "PR",
    iso: "PR",
    flag: "🇵🇷",
    name: "Puerto Rico",
  },
  {
    key: "PS",
    iso: "PS",
    flag: "🇵🇸",
    name: "Palestinian Territory",
  },
  {
    key: "PT",
    iso: "PT",
    flag: "🇵🇹",
    name: "Portugal",
  },
  {
    key: "PW",
    iso: "PW",
    flag: "🇵🇼",
    name: "Palau",
  },
  {
    key: "PY",
    iso: "PY",
    flag: "🇵🇾",
    name: "Paraguay",
  },
  {
    key: "QA",
    iso: "QA",
    flag: "🇶🇦",
    name: "Qatar",
  },
  {
    key: "RE",
    iso: "RE",
    flag: "🇷🇪",
    name: "Réunion",
  },
  {
    key: "RO",
    iso: "RO",
    flag: "🇷🇴",
    name: "Romania",
  },
  {
    key: "RS",
    iso: "RS",
    flag: "🇷🇸",
    name: "Serbia",
  },
  {
    key: "RU",
    iso: "RU",
    flag: "🇷🇺",
    name: "Russia",
  },
  {
    key: "RW",
    iso: "RW",
    flag: "🇷🇼",
    name: "Rwanda",
  },
  {
    key: "SA",
    iso: "SA",
    flag: "🇸🇦",
    name: "Saudi Arabia",
  },
  {
    key: "SB",
    iso: "SB",
    flag: "🇸🇧",
    name: "Solomon Islands",
  },
  {
    key: "SC",
    iso: "SC",
    flag: "🇸🇨",
    name: "Seychelles",
  },
  {
    key: "SD",
    iso: "SD",
    flag: "🇸🇩",
    name: "Sudan",
  },
  {
    key: "SE",
    iso: "SE",
    flag: "🇸🇪",
    name: "Sweden",
  },
  {
    key: "SG",
    iso: "SG",
    flag: "🇸🇬",
    name: "Singapore",
  },
  {
    key: "SH",
    iso: "SH",
    flag: "🇸🇭",
    name: "Saint Helena, Ascension and Tristan Da Cunha",
  },
  {
    key: "SI",
    iso: "SI",
    flag: "🇸🇮",
    name: "Slovenia",
  },
  {
    key: "SJ",
    iso: "SJ",
    flag: "🇸🇯",
    name: "Svalbard and Jan Mayen",
  },
  {
    key: "SK",
    iso: "SK",
    flag: "🇸🇰",
    name: "Slovakia",
  },
  {
    key: "SL",
    iso: "SL",
    flag: "🇸🇱",
    name: "Sierra Leone",
  },
  {
    key: "SM",
    iso: "SM",
    flag: "🇸🇲",
    name: "San Marino",
  },
  {
    key: "SN",
    iso: "SN",
    flag: "🇸🇳",
    name: "Senegal",
  },
  {
    key: "SO",
    iso: "SO",
    flag: "🇸🇴",
    name: "Somalia",
  },
  {
    key: "SR",
    iso: "SR",
    flag: "🇸🇷",
    name: "Suriname",
  },
  {
    key: "SS",
    iso: "SS",
    flag: "🇸🇸",
    name: "South Sudan",
  },
  {
    key: "ST",
    iso: "ST",
    flag: "🇸🇹",
    name: "Sao Tome and Principe",
  },
  {
    key: "SV",
    iso: "SV",
    flag: "🇸🇻",
    name: "El Salvador",
  },
  {
    key: "SX",
    iso: "SX",
    flag: "🇸🇽",
    name: "Sint Maarten (Dutch Part)",
  },
  {
    key: "SY",
    iso: "SY",
    flag: "🇸🇾",
    name: "Syrian Arab Republic",
  },
  {
    key: "SZ",
    iso: "SZ",
    flag: "🇸🇿",
    name: "Swaziland",
  },
  {
    key: "TC",
    iso: "TC",
    flag: "🇹🇨",
    name: "Turks and Caicos Islands",
  },
  {
    key: "TD",
    iso: "TD",
    flag: "🇹🇩",
    name: "Chad",
  },
  {
    key: "TF",
    iso: "TF",
    flag: "🇹🇫",
    name: "French Southern Territories",
  },
  {
    key: "TG",
    iso: "TG",
    flag: "🇹🇬",
    name: "Togo",
  },
  {
    key: "TH",
    iso: "TH",
    flag: "🇹🇭",
    name: "Thailand",
  },
  {
    key: "TJ",
    iso: "TJ",
    flag: "🇹🇯",
    name: "Tajikistan",
  },
  {
    key: "TK",
    iso: "TK",
    flag: "🇹🇰",
    name: "Tokelau",
  },
  {
    key: "TL",
    iso: "TL",
    flag: "🇹🇱",
    name: "Timor-Leste",
  },
  {
    key: "TM",
    iso: "TM",
    flag: "🇹🇲",
    name: "Turkmenistan",
  },
  {
    key: "TN",
    iso: "TN",
    flag: "🇹🇳",
    name: "Tunisia",
  },
  {
    key: "TO",
    iso: "TO",
    flag: "🇹🇴",
    name: "Tonga",
  },
  {
    key: "TR",
    iso: "TR",
    flag: "🇹🇷",
    name: "Turkey",
  },
  {
    key: "TT",
    iso: "TT",
    flag: "🇹🇹",
    name: "Trinidad and Tobago",
  },
  {
    key: "TV",
    iso: "TV",
    flag: "🇹🇻",
    name: "Tuvalu",
  },
  {
    key: "TW",
    iso: "TW",
    flag: "🇹🇼",
    name: "Taiwan",
  },
  {
    key: "TZ",
    iso: "TZ",
    flag: "🇹🇿",
    name: "Tanzania",
  },
  {
    key: "UA",
    iso: "UA",
    flag: "🇺🇦",
    name: "Ukraine",
  },
  {
    key: "UG",
    iso: "UG",
    flag: "🇺🇬",
    name: "Uganda",
  },
  {
    key: "UM",
    iso: "UM",
    flag: "🇺🇲",
    name: "United States Minor Outlying Islands",
  },
  {
    key: "US",
    iso: "US",
    flag: "🇺🇸",
    name: "United States",
  },
  {
    key: "UY",
    iso: "UY",
    flag: "🇺🇾",
    name: "Uruguay",
  },
  {
    key: "UZ",
    iso: "UZ",
    flag: "🇺🇿",
    name: "Uzbekistan",
  },
  {
    key: "VA",
    iso: "VA",
    flag: "🇻🇦",
    name: "Vatican City",
  },
  {
    key: "VC",
    iso: "VC",
    flag: "🇻🇨",
    name: "Saint Vincent and The Grenadines",
  },
  {
    key: "VE",
    iso: "VE",
    flag: "🇻🇪",
    name: "Venezuela",
  },
  {
    key: "VG",
    iso: "VG",
    flag: "🇻🇬",
    name: "Virgin Islands, British",
  },
  {
    key: "VI",
    iso: "VI",
    flag: "🇻🇮",
    name: "Virgin Islands, U.S.",
  },
  {
    key: "VN",
    iso: "VN",
    flag: "🇻🇳",
    name: "Viet Nam",
  },
  {
    key: "VU",
    iso: "VU",
    flag: "🇻🇺",
    name: "Vanuatu",
  },
  {
    key: "WF",
    iso: "WF",
    flag: "🇼🇫",
    name: "Wallis and Futuna",
  },
  {
    key: "WS",
    iso: "WS",
    flag: "🇼🇸",
    name: "Samoa",
  },
  {
    key: "YE",
    iso: "YE",
    flag: "🇾🇪",
    name: "Yemen",
  },
  {
    key: "YT",
    iso: "YT",
    flag: "🇾🇹",
    name: "Mayotte",
  },
  {
    key: "ZA",
    iso: "ZA",
    flag: "🇿🇦",
    name: "South Africa",
  },
  {
    key: "ZM",
    iso: "ZM",
    flag: "🇿🇲",
    name: "Zambia",
  },
  {
    key: "ZW",
    iso: "ZW",
    flag: "🇿🇼",
    name: "Zimbabwe",
  },
];

export const countryToFlag = {
  Andorra: "🇦🇩",
  "United Arab Emirates": "🇦🇪",
  Afghanistan: "🇦🇫",
  "Antigua and Barbuda": "🇦🇬",
  Anguilla: "🇦🇮",
  Albania: "🇦🇱",
  Armenia: "🇦🇲",
  Angola: "🇦🇴",
  Antarctica: "🇦🇶",
  Argentina: "🇦🇷",
  "American Samoa": "🇦🇸",
  Austria: "🇦🇹",
  Australia: "🇦🇺",
  Aruba: "🇦🇼",
  "Åland Islands": "🇦🇽",
  Azerbaijan: "🇦🇿",
  "Bosnia and Herzegovina": "🇧🇦",
  Barbados: "🇧🇧",
  Bangladesh: "🇧🇩",
  Belgium: "🇧🇪",
  "Burkina Faso": "🇧🇫",
  Bulgaria: "🇧🇬",
  Bahrain: "🇧🇭",
  Burundi: "🇧🇮",
  Benin: "🇧🇯",
  "Saint Barthélemy": "🇧🇱",
  Bermuda: "🇧🇲",
  "Brunei Darussalam": "🇧🇳",
  Bolivia: "🇧🇴",
  "Bonaire, Sint Eustatius and Saba": "🇧🇶",
  Brazil: "🇧🇷",
  Bahamas: "🇧🇸",
  Bhutan: "🇧🇹",
  "Bouvet Island": "🇧🇻",
  Botswana: "🇧🇼",
  Belarus: "🇧🇾",
  Belize: "🇧🇿",
  Canada: "🇨🇦",
  "Cocos (Keeling) Islands": "🇨🇨",
  "Congo Kinshasa": "🇨🇩",
  "Central African Republic": "🇨🇫",
  "Congo Brazzaville": "🇨🇬",
  Switzerland: "🇨🇭",
  "Côte D'Ivoire": "🇨🇮",
  "Cook Islands": "🇨🇰",
  Chile: "🇨🇱",
  Cameroon: "🇨🇲",
  China: "🇨🇳",
  Colombia: "🇨🇴",
  "Costa Rica": "🇨🇷",
  Cuba: "🇨🇺",
  "Cape Verde": "🇨🇻",
  Curaçao: "🇨🇼",
  "Christmas Island": "🇨🇽",
  Cyprus: "🇨🇾",
  "Czech Republic": "🇨🇿",
  Germany: "🇩🇪",
  Djibouti: "🇩🇯",
  Denmark: "🇩🇰",
  Dominica: "🇩🇲",
  "Dominican Republic": "🇩🇴",
  Algeria: "🇩🇿",
  Ecuador: "🇪🇨",
  Estonia: "🇪🇪",
  Egypt: "🇪🇬",
  "Western Sahara": "🇪🇭",
  Eritrea: "🇪🇷",
  Spain: "🇪🇸",
  Ethiopia: "🇪🇹",
  Finland: "🇫🇮",
  Fiji: "🇫🇯",
  "Falkland Islands (Malvinas)": "🇫🇰",
  Micronesia: "🇫🇲",
  "Faroe Islands": "🇫🇴",
  France: "🇫🇷",
  Gabon: "🇬🇦",
  "United Kingdom": "🇬🇧",
  Grenada: "🇬🇩",
  Georgia: "🇬🇪",
  "French Guiana": "🇬🇫",
  Guernsey: "🇬🇬",
  Ghana: "🇬🇭",
  Gibraltar: "🇬🇮",
  Greenland: "🇬🇱",
  Gambia: "🇬🇲",
  Guinea: "🇬🇳",
  Guadeloupe: "🇬🇵",
  "Equatorial Guinea": "🇬🇶",
  Greece: "🇬🇷",
  "South Georgia": "🇬🇸",
  Guatemala: "🇬🇹",
  Guam: "🇬🇺",
  "Guinea-Bissau": "🇬🇼",
  Guyana: "🇬🇾",
  "Hong Kong": "🇭🇰",
  "Heard Island and Mcdonald Islands": "🇭🇲",
  Honduras: "🇭🇳",
  Croatia: "🇭🇷",
  Haiti: "🇭🇹",
  Hungary: "🇭🇺",
  Indonesia: "🇮🇩",
  Ireland: "🇮🇪",
  Israel: "🇮🇱",
  "Isle of Man": "🇮🇲",
  India: "🇮🇳",
  "British Indian Ocean Territory": "🇮🇴",
  Iraq: "🇮🇶",
  Iran: "🇮🇷",
  Iceland: "🇮🇸",
  Italy: "🇮🇹",
  Jersey: "🇯🇪",
  Jamaica: "🇯🇲",
  Jordan: "🇯🇴",
  Japan: "🇯🇵",
  Kenya: "🇰🇪",
  Kyrgyzstan: "🇰🇬",
  Cambodia: "🇰🇭",
  Kiribati: "🇰🇮",
  Comoros: "🇰🇲",
  "Saint Kitts and Nevis": "🇰🇳",
  "North Korea": "🇰🇵",
  "South Korea": "🇰🇷",
  Kuwait: "🇰🇼",
  "Cayman Islands": "🇰🇾",
  Kazakhstan: "🇰🇿",
  "Lao People's Democratic Republic": "🇱🇦",
  Lebanon: "🇱🇧",
  "Saint Lucia": "🇱🇨",
  Liechtenstein: "🇱🇮",
  "Sri Lanka": "🇱🇰",
  Liberia: "🇱🇷",
  Lesotho: "🇱🇸",
  Lithuania: "🇱🇹",
  Luxembourg: "🇱🇺",
  Latvia: "🇱🇻",
  Libya: "🇱🇾",
  Morocco: "🇲🇦",
  Monaco: "🇲🇨",
  Moldova: "🇲🇩",
  Montenegro: "🇲🇪",
  "Saint Martin (French Part)": "🇲🇫",
  Madagascar: "🇲🇬",
  "Marshall Islands": "🇲🇭",
  Macedonia: "🇲🇰",
  Mali: "🇲🇱",
  Myanmar: "🇲🇲",
  Mongolia: "🇲🇳",
  Macao: "🇲🇴",
  "Northern Mariana Islands": "🇲🇵",
  Martinique: "🇲🇶",
  Mauritania: "🇲🇷",
  Montserrat: "🇲🇸",
  Malta: "🇲🇹",
  Mauritius: "🇲🇺",
  Maldives: "🇲🇻",
  Malawi: "🇲🇼",
  Mexico: "🇲🇽",
  Malaysia: "🇲🇾",
  Mozambique: "🇲🇿",
  Namibia: "🇳🇦",
  "New Caledonia": "🇳🇨",
  Niger: "🇳🇪",
  "Norfolk Island": "🇳🇫",
  Nigeria: "🇳🇬",
  Nicaragua: "🇳🇮",
  Netherlands: "🇳🇱",
  Norway: "🇳🇴",
  Nepal: "🇳🇵",
  Nauru: "🇳🇷",
  Niue: "🇳🇺",
  "New Zealand": "🇳🇿",
  Oman: "🇴🇲",
  Panama: "🇵🇦",
  Peru: "🇵🇪",
  "French Polynesia": "🇵🇫",
  "Papua New Guinea": "🇵🇬",
  Philippines: "🇵🇭",
  Pakistan: "🇵🇰",
  Poland: "🇵🇱",
  "Saint Pierre and Miquelon": "🇵🇲",
  Pitcairn: "🇵🇳",
  "Puerto Rico": "🇵🇷",
  "Palestinian Territory": "🇵🇸",
  Portugal: "🇵🇹",
  Palau: "🇵🇼",
  Paraguay: "🇵🇾",
  Qatar: "🇶🇦",
  Réunion: "🇷🇪",
  Romania: "🇷🇴",
  Serbia: "🇷🇸",
  Russia: "🇷🇺",
  Rwanda: "🇷🇼",
  "Saudi Arabia": "🇸🇦",
  "Solomon Islands": "🇸🇧",
  Seychelles: "🇸🇨",
  Sudan: "🇸🇩",
  Sweden: "🇸🇪",
  Singapore: "🇸🇬",
  "Saint Helena, Ascension and Tristan Da Cunha": "🇸🇭",
  Slovenia: "🇸🇮",
  "Svalbard and Jan Mayen": "🇸🇯",
  Slovakia: "🇸🇰",
  "Sierra Leone": "🇸🇱",
  "San Marino": "🇸🇲",
  Senegal: "🇸🇳",
  Somalia: "🇸🇴",
  Suriname: "🇸🇷",
  "South Sudan": "🇸🇸",
  "Sao Tome and Principe": "🇸🇹",
  "El Salvador": "🇸🇻",
  "Sint Maarten (Dutch Part)": "🇸🇽",
  "Syrian Arab Republic": "🇸🇾",
  Swaziland: "🇸🇿",
  "Turks and Caicos Islands": "🇹🇨",
  Chad: "🇹🇩",
  "French Southern Territories": "🇹🇫",
  Togo: "🇹🇬",
  Thailand: "🇹🇭",
  Tajikistan: "🇹🇯",
  Tokelau: "🇹🇰",
  "Timor-Leste": "🇹🇱",
  Turkmenistan: "🇹🇲",
  Tunisia: "🇹🇳",
  Tonga: "🇹🇴",
  Turkey: "🇹🇷",
  "Trinidad and Tobago": "🇹🇹",
  Tuvalu: "🇹🇻",
  Taiwan: "🇹🇼",
  Tanzania: "🇹🇿",
  Ukraine: "🇺🇦",
  Uganda: "🇺🇬",
  "United States Minor Outlying Islands": "🇺🇲",
  "United States": "🇺🇸",
  Uruguay: "🇺🇾",
  Uzbekistan: "🇺🇿",
  "Vatican City": "🇻🇦",
  "Saint Vincent and The Grenadines": "🇻🇨",
  Venezuela: "🇻🇪",
  "Virgin Islands, British": "🇻🇬",
  "Virgin Islands, U.S.": "🇻🇮",
  "Viet Nam": "🇻🇳",
  Vanuatu: "🇻🇺",
  "Wallis and Futuna": "🇼🇫",
  Samoa: "🇼🇸",
  Yemen: "🇾🇪",
  Mayotte: "🇾🇹",
  "South Africa": "🇿🇦",
  Zambia: "🇿🇲",
  Zimbabwe: "🇿🇼",
};

const Flag: FC<FlagProps> = (props) => {
  const { name, code = "US", ...rest } = props;

  const getFlag = () => {
    if (name) {
      return countryToFlag[name as keyof typeof countryToFlag];
    }

    return countryOptions.find(({ iso }) => iso === code)?.flag;
  };

  return <Text {...rest}>{getFlag()}</Text>;
};

// ======================================================
export interface FlagProps {
  [k: string]: any;

  /** Country code. */
  code?: CountryCode;

  /** Country name. */
  name?: CountryName;

  /** Custom styles. */
  style?: TextStyle;
}

export default Flag;
