name: release

on:
  push:
    paths-ignore:
      - "CHANGELOG.md"
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: |
          yarn --frozen-lockfile

      - name: Release and Publish
        id: release
        run: |
          yarn run release
        continue-on-error: false
        env:
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GUI_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
